name: Deploy Gym Booking Function

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: ${{ secrets.AZURE_FUNCTIONAPP_NAME }}
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "."
  AZURE_APPCONFIG_NAME: ${{ secrets.AZURE_APPCONFIG_NAME }}
  PYTHON_VERSION: "3.13"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v3

      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: "Resolve Project Dependencies Using Pip"
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          python -m pip install --upgrade pip
          pip install -r requirements.txt --target=".python_packages/lib/site-packages"
          popd

      - name: "Log in to Azure"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: "Update Function App Settings"
        run: |
          az functionapp config appsettings set --name ${{ env.AZURE_FUNCTIONAPP_NAME }} --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --settings \
            USER0_USERNAME="${{ secrets.USER0_USERNAME }}" \
            USER0_PASSWORD="${{ secrets.USER0_PASSWORD }}" \
            USER1_USERNAME="${{ secrets.USER1_USERNAME }}" \
            USER1_PASSWORD="${{ secrets.USER1_PASSWORD }}" \
            AZURE_APP_CONFIG_ENDPOINT="${{ secrets.AZURE_APP_CONFIG_ENDPOINT }}" \
            WEBSITE_TIME_ZONE="Europe/Luxembourg"

      - name: "Update App Configuration"
        run: |
          az appconfig kv set --name ${{ env.AZURE_APPCONFIG_NAME }} --key "app_id" --value "EC1D38D7-D359-48D0-A60C-D8C0B8FB9DF9" --yes --auth-mode login
          az appconfig kv set --name ${{ env.AZURE_APPCONFIG_NAME }} --key "client" --value "enduserweb" --yes --auth-mode login
          az appconfig kv set --name ${{ env.AZURE_APPCONFIG_NAME }} --key "client_version" --value "1.13.10-1629,enduserweb" --yes --auth-mode login
          az appconfig kv set --name ${{ env.AZURE_APPCONFIG_NAME }} --key "facility_id" --value "334e683b-fd35-4076-95be-c32c233d1e46" --yes --auth-mode login

          az appconfig kv set --name ${{ env.AZURE_APPCONFIG_NAME }} --key "users" --value '${{ vars.USERS_CONFIG_JSON }}' --content-type "application/json" --yes --auth-mode login
          az appconfig kv set --name ${{ env.AZURE_APPCONFIG_NAME }} --key "classes" --value '${{ vars.CLASSES_CONFIG_JSON }}' --content-type "application/json" --yes --auth-mode login

      - name: "Run Azure Functions Action"
        uses: azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          scm-do-build-during-deployment: true
          enable-oryx-build: true
